# Custom Language File for Launcher Customizer

[ejs.app]
title = "ZeroProject Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Frame121-DEV"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/G3U7caRY"

[ejs.settings]
sourceGithubLink = "https://github.com/Frame121-DEV"
supportLink = "https://github.com/Frame121-DEV"

[ejs.welcome]
welcomeHeader = "WELCOME TO ZeroProject"
welcomeDescription = "ZeroProject-Launcher พัฒนาโดย ZeroProject-Developer"
welcomeDescCTA = "( Credit By Helios-Launcher )"
